---
# tasks file for ansible-role-batman
- name: Install B.A.T.M.A.N.-adv kernel modules
  include_tasks: kernel.yml

- name: Configure B.A.T.M.A.N.-adv
  include_tasks: config.yml

- name: Install and configure dnsmasq as DHCP server for the mesh
  include_tasks: dnsmasq.yml
  when: inventory_hostname in groups['dhcp']|default([])
